### ISSUE TITLE
Following the Readme leeds to an `ERROR: Assembly not found.`

### ISSUE THREAD

**Issue by basbossink** [scriptcs-contrib/scriptcs-nunit#1]
When trying out this package using the instructions found in the Readme running 

```
scriptcs start.csx -debug
```

gives to the following output:

```
ERROR: Assembly not found.
```

Running the nunit-runner sample from the scriptcs-samples repository gives the same result.

**Comment by Andrea** [comment]
Same here I get the Assembly not found - nunit.core.dll 
I ll update if I find a workaround

**Comment by filipw** [comment]
the readme was out of date (using old versions of packages). Please install from nuget using `scriptcs -install scriptcs.nunit`
